USE sakila;

-- 1. List the number of films per category
SELECT
	c.name AS category,
	COUNT(fc.film_id) AS number_of_films
FROM category c
JOIN film_category fc
	ON c.category_id =  fc.category_id
GROUP BY c.name;

-- 2. Retrieve the store ID, city, and country for each store
SELECT 
	s.store_id,
    ci.city,
    co.country
FROM store s
JOIN address a
	ON s.address_id = a.address_id
JOIN city ci
	ON a.city_id = ci.city_id
JOIN country co
	ON ci.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store
SELECT
	s.store_id,
    SUM(p.amount) AS total_revenue
FROM store s
JOIN staff st
	ON s.store_id =st.store_id
JOIN payment p
	ON st.staff_id = p.staff_id
GROUP BY s.store_id;

-- 4. Determine the average running time of films for each category
SELECT
	c.name,
    ROUND(AVG(f.length),2) AS average_running_time
FROM category c
JOIN film_category fc
	ON c.category_id = fc.category_id
JOIN film f
	ON fc.film_id = f.film_id
GROUP BY c.name;

-- BONUS 1. Film categories with the longest average running time
SELECT
	c.name,
    ROUND(AVG(f.length),2) AS average_running_time
FROM category c
JOIN film_category fc
	ON c.category_id = fc.category_id
JOIN film f
	ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY average_running_time DESC;

-- BONUS 2. Top 10 most frequently rented movies
SELECT
	f.title,
    COUNT(rental_id) AS rental_count
FROM film f
JOIN inventory i
		ON f.film_id = i.film_id
JOIN rental r
	ON i.inventory_id = r.inventory_id
GROUP BY f.title
ORDER BY rental_count DESC
LIMIT 10;

-- BONUS 3. Determine if "Academy Dinosaur" can be rented from Store 1
SELECT
	f.title,
    i.store_id,
    CASE
		WHEN COUNT(i.inventory_id) > 0 THEN 'Available'
        ELSE 'Not available'
    END AS availability
FROM film f
JOIN inventory i
	ON f.film_id = i.film_id
WHERE f.title = 'Academy Dinosaur'
AND i.store_id = 1
GROUP BY f.title, i.store_id;

-- BONUS 4. Distinct film titles with availability status
SELECT
	f.title,
    CASE
		WHEN IFNULL(i.inventory_id, 0) = 0 THEN 'Not available'
        ELSE 'Available'
	END AS availability
FROM film f
LEFT JOIN inventory i
	ON f.film_id = i.film_id
GROUP BY f.title, availability
ORDER BY f.title;






